"""empty message

Revision ID: 8a3e848a867a
Revises: 
Create Date: 2023-07-25 08:51:05.196395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e848a867a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_lampu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_lampu', sa.String(length=50), nullable=True),
    sa.Column('status_lampu', sa.Integer(), nullable=True),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_lampu')
    # ### end Alembic commands ###
